name: Continuous Deployment
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - run: echo "Please visit => ${{ secrets.SURGE_DOMAIN }}"
